name: AusyPlugs
favicon: null
layout_spectrum: 0.49659
typography_spectrum: 0.48987
title: Ausy Ceramic Plugs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0d11'
    - '#d0c5b0'
    - '#9da9fd'
    - '#439094'
    - '#6c2b2e'
  brandStrength: 0.0625
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
