name: AusyPlugs
favicon: null
layout_spectrum: 0.50045
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000405'
    - '#695b52'
    - '#a1938a'
    - '#860005'
    - '#e43e53'
  brandStrength: 0.0704132760874927
  lightness: 0.6030253167264163
  saturation: 0.32725933007895947
  rhythmicContrast: 0.5780345466919243
purpose: []
