name: AusyPlugs
favicon: null
layout_spectrum: 0.49659
typography_spectrum: 0.48987
title: Handmade Ceramic Flesh Tunnel Plugs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#443a30'
    - '#d9dde0'
    - '#5e86c3'
    - '#7e705e'
  brandStrength: 0.0625
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
